name: Continuous integration
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * THU'

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        drupal_version: ['8.9', '9.0', '9.1', '9.2', '9.3', '9.4', '9.5']
        module: ['timesup']
        experimental: [ false ]
        include:
          - drupal_version: '9.5'
            module: 'timesup'
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose.yml pull --include-deps drupal
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml build --pull --build-arg BASE_IMAGE_TAG=${{ matrix.drupal_version }} drupal
        continue-on-error: ${{ matrix.experimental }}
      - name: Run unit tests
        run: docker-compose -f docker-compose.yml run -u www-data drupal phpunit --no-coverage --group=${{ matrix.module }} --exclude-group=${{ matrix.module }}_functional --configuration=/var/www/html/phpunit.xml
        continue-on-error: ${{ matrix.experimental }}

  upgrade-status:
    name: Upgrade Status
    runs-on: ubuntu-latest

    strategy:
      matrix:
        drupal_version: ['9.4']
        module: ['timesup']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: docker-compose -f docker-compose.yml pull --include-deps drupal
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml build --pull --build-arg BASE_IMAGE_TAG=${{ matrix.drupal_version }} drupal
      - name: Up a persistent Docker Container
        run: docker-compose -f docker-compose.yml up -d drupal
      - name: Add upgrade status dependency
        run: docker-compose exec -T drupal wait-for-it db:3306 -- composer require --dev drupal/upgrade_status --no-interaction
      - name: Bootstrap Drupal
        run: docker-compose -f docker-compose.yml exec -T -u www-data drupal drush site-install standard --db-url="mysql://drupal:drupal@db/drupal" -y
      - name: Enable upgrade status
        run: docker-compose exec -T drupal wait-for-it db:3306 -- ./vendor/bin/drush en upgrade_status -y
      - name: Disable incompatible module
        run: docker-compose exec -T drupal wait-for-it db:3306 -- ./vendor/bin/drush pmu page_cache -y
      - name: Enable the module
        run: docker-compose exec -T drupal wait-for-it db:3306 -- ./vendor/bin/drush en ${{ matrix.module }} -y
      - name: Run upgrade status
        run: docker-compose exec -T drupal wait-for-it db:3306 -- ./vendor/bin/drush upgrade_status:analyze ${{ matrix.module }}
